/**
 * 기본 연습문제 20개.
 *
 * 선생님의 수업 노트북(파이썬(교사)/01~08, 튜플, 터틀)을 읽고 진도에 맞춰 만들었다 —
 * 모범답안은 노트북에 나오지 않은 문법(f스트링, [::-1], round, max/sum,
 * 리스트 컴프리헨션)을 쓰지 않는다. 새 문제를 더할 때도 이 범위를 지킬 것.
 *
 * 기대 출력(expected)은 손으로 적은 값이 아니다 — 모범답안을 실제로 실행해서
 * 받아 적었다. 공백 하나 때문에 정답이 오답 처리되는 사고를 막는 유일한 방법이라,
 * 교사 화면에서 문제를 만들 때도 같은 방식으로 채운다(ExerciseEditor 참고).
 *
 * 이 파일은 "처음 한 번 Firestore 에 넣을 씨앗"이다. 넣고 나면 교사 페이지에서
 * 고치고 지울 수 있고, 이 파일은 더 읽히지 않는다.
 */
import type { ExerciseDraft } from '../lib/exercises'

export const DEFAULT_EXERCISES: ExerciseDraft[] = [
  {
    order: 1,
    title: "인사 출력",
    concept: "print",
    body: "화면에 아래 문장을 그대로 출력하세요.\n\n```\n안녕하세요, 파이썬!\n```",
    io: "- 입력: 없음\n- 출력: 위 문장 한 줄",
    hint: "따옴표 안의 내용이 그대로 나옵니다. 쉼표와 느낌표도 빠뜨리지 마세요.",
    answer: "print(\"안녕하세요, 파이썬!\")",
    tests: [
      { stdin: "", expected: "안녕하세요, 파이썬!", hidden: false },
    ],
    published: true,
  },
  {
    order: 2,
    title: "두 수의 합",
    concept: "input, int, 사칙연산",
    body: "정수 두 개를 입력받아 합을 출력하세요.",
    io: "- 입력: 첫째 줄에 a, 둘째 줄에 b\n- 출력: a + b",
    hint: "`input()` 이 주는 것은 글자입니다. `int()` 로 숫자로 바꿔야 더할 수 있습니다.",
    answer: "a = int(input())\nb = int(input())\nprint(a + b)",
    tests: [
      { stdin: "3\n5", expected: "8", hidden: false },
      { stdin: "-2\n7", expected: "5", hidden: true },
      { stdin: "100\n200", expected: "300", hidden: true },
    ],
    published: true,
  },
  {
    order: 3,
    title: "직사각형의 넓이와 둘레",
    concept: "여러 줄 출력, 식 세우기",
    body: "가로와 세로를 입력받아 넓이와 둘레를 각각 한 줄씩 출력하세요.",
    io: "- 입력: 첫째 줄 가로, 둘째 줄 세로\n- 출력: 첫째 줄 넓이, 둘째 줄 둘레",
    hint: "둘레는 (가로+세로)를 두 배 하면 됩니다.",
    answer: "w = int(input())\nh = int(input())\nprint(w * h)\nprint(2 * (w + h))",
    tests: [
      { stdin: "3\n4", expected: "12\n14", hidden: false },
      { stdin: "5\n5", expected: "25\n20", hidden: true },
      { stdin: "10\n2", expected: "20\n24", hidden: true },
    ],
    published: true,
  },
  {
    order: 4,
    title: "홀수일까 짝수일까",
    concept: "if / else, 나머지 연산 %",
    body: "정수 하나를 입력받아 짝수면 `짝수`, 홀수면 `홀수` 를 출력하세요.",
    io: "- 입력: 정수 하나\n- 출력: `짝수` 또는 `홀수`",
    hint: "2로 나눈 나머지가 0이면 짝수입니다. 0도 짝수라는 걸 잊지 마세요.",
    answer: "n = int(input())\nif n % 2 == 0:\n  print(\"짝수\")\nelse:\n  print(\"홀수\")",
    tests: [
      { stdin: "4", expected: "짝수", hidden: false },
      { stdin: "7", expected: "홀수", hidden: true },
      { stdin: "0", expected: "짝수", hidden: true },
    ],
    published: true,
  },
  {
    order: 5,
    title: "성적 등급 매기기",
    concept: "if / elif / else",
    body: "점수를 입력받아 등급을 출력하세요.\n90 이상 A, 80 이상 B, 70 이상 C, 60 이상 D, 그 미만 F 입니다.",
    io: "- 입력: 점수 하나 (0~100)\n- 출력: 등급 한 글자",
    hint: "숨김 테스트에 90점과 60점이 있습니다 — '이상'과 '초과'를 헷갈리면 여기서 걸립니다.",
    answer: "score = int(input())\nif score >= 90:\n  print(\"A\")\nelif score >= 80:\n  print(\"B\")\nelif score >= 70:\n  print(\"C\")\nelif score >= 60:\n  print(\"D\")\nelse:\n  print(\"F\")",
    tests: [
      { stdin: "85", expected: "B", hidden: false },
      { stdin: "90", expected: "A", hidden: true },
      { stdin: "60", expected: "D", hidden: true },
      { stdin: "59", expected: "F", hidden: true },
    ],
    published: true,
  },
  {
    order: 6,
    title: "1부터 N까지 더하기",
    concept: "for, range, 누적",
    body: "N을 입력받아 1부터 N까지의 합을 출력하세요.",
    io: "- 입력: 정수 N\n- 출력: 합",
    hint: "`range(1, n)` 은 n을 포함하지 않습니다. `n + 1` 까지 적어야 N이 더해집니다.",
    answer: "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n  total += i\nprint(total)",
    tests: [
      { stdin: "10", expected: "55", hidden: false },
      { stdin: "1", expected: "1", hidden: true },
      { stdin: "100", expected: "5050", hidden: true },
    ],
    published: true,
  },
  {
    order: 7,
    title: "구구단 출력하기",
    concept: "for, 출력 형식 맞추기",
    body: "단을 입력받아 그 단을 1부터 9까지 출력하세요.\n형식은 `3 x 1 = 3` 처럼 **곱셈기호와 등호 앞뒤에 공백 한 칸씩**입니다.",
    io: "- 입력: 단 (2~9)\n- 출력: 9줄",
    hint: "`print` 에 쉼표로 여러 개를 넘기면 사이에 공백 한 칸이 자동으로 들어갑니다. 그래서 `print(n, \"x\", i, \"=\", n * i)` 만으로 형식이 맞습니다. `x` 는 알파벳 소문자입니다.",
    answer: "n = int(input())\nfor i in range(1, 10):\n  print(n, \"x\", i, \"=\", n * i)",
    tests: [
      { stdin: "3", expected: "3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27", hidden: false },
      { stdin: "7", expected: "7 x 1 = 7\n7 x 2 = 14\n7 x 3 = 21\n7 x 4 = 28\n7 x 5 = 35\n7 x 6 = 42\n7 x 7 = 49\n7 x 8 = 56\n7 x 9 = 63", hidden: true },
    ],
    published: true,
  },
  {
    order: 8,
    title: "별 삼각형",
    concept: "반복 안에서 값이 바뀌는 출력, 문자열 곱하기",
    body: "N을 입력받아 별을 1개부터 N개까지 한 줄씩 늘려가며 출력하세요.",
    io: "- 입력: 정수 N\n- 출력: N줄",
    hint: "문자열에 숫자를 곱하면 그 횟수만큼 이어붙습니다.",
    answer: "n = int(input())\nfor i in range(1, n + 1):\n  print(\"*\" * i)",
    tests: [
      { stdin: "3", expected: "*\n**\n***", hidden: false },
      { stdin: "1", expected: "*", hidden: true },
      { stdin: "5", expected: "*\n**\n***\n****\n*****", hidden: true },
    ],
    published: true,
  },
  {
    order: 9,
    title: "점수 통계 (최고점과 평균)",
    concept: "split, 리스트 훑기, 누적, 나눗셈",
    body: "학생 수와 점수들을 입력받아 최고점과 평균을 출력하세요.",
    io: "- 입력: 첫째 줄에 사람 수 N, 둘째 줄에 점수 N개 (공백으로 구분, 각 점수는 0~100)\n- 출력: 첫째 줄 최고점, 둘째 줄 평균",
    hint: "`input().split()` 은 공백으로 잘라 여러 조각을 줍니다. 조각은 아직 글자라서 `int()` 로 바꿔야 더할 수 있습니다. 나눗셈 결과는 `87.5` 처럼 소수로 나옵니다.",
    note: "`map` 을 배웠다면 `scores = list(map(int, input().split()))` 로 짧게 쓸 수 있습니다.",
    answer: "n = int(input())\nscores = input().split()\n\ntotal = 0\nbest = 0\nfor s in scores:\n  score = int(s)\n  total += score\n  if score > best:\n    best = score\n\nprint(best)\nprint(total / n)",
    tests: [
      { stdin: "4\n90 85 100 75", expected: "100\n87.5", hidden: false },
      { stdin: "3\n70 80 90", expected: "90\n80.0", hidden: true },
      { stdin: "1\n55", expected: "55\n55.0", hidden: true },
    ],
    published: true,
  },
  {
    order: 10,
    title: "거꾸로 읽기와 모음 세기",
    concept: "문자열을 한 글자씩 다루기, 반복, 조건",
    body: "영어 소문자 단어 하나를 입력받아, 뒤집은 단어와 모음(a, e, i, o, u) 개수를 출력하세요.",
    io: "- 입력: 영어 소문자 단어\n- 출력: 첫째 줄 뒤집은 단어, 둘째 줄 모음 개수",
    hint: "뒤집기는 빈 문자열에서 시작해 새 글자를 **앞에** 붙여 나가면 됩니다 — `ch + reversed_word` 의 순서가 핵심입니다. 모음이 하나도 없을 수도 있습니다.",
    note: "`in` 을 배웠다면 모음 판별은 `if ch in \"aeiou\":` 한 줄로 줄어듭니다.",
    answer: "word = input()\n\nreversed_word = \"\"\nfor ch in word:\n  reversed_word = ch + reversed_word\nprint(reversed_word)\n\ncount = 0\nfor ch in word:\n  if ch == \"a\" or ch == \"e\" or ch == \"i\" or ch == \"o\" or ch == \"u\":\n    count += 1\nprint(count)",
    tests: [
      { stdin: "python", expected: "nohtyp\n1", hidden: false },
      { stdin: "banana", expected: "ananab\n3", hidden: true },
      { stdin: "sky", expected: "yks\n0", hidden: true },
    ],
    published: true,
  },
  {
    order: 11,
    title: "FizzBuzz",
    concept: "조건문과 반복문 종합, 조건의 순서",
    body: "1부터 N까지 한 줄씩 출력하되,\n3의 배수는 `Fizz`, 5의 배수는 `Buzz`, 3과 5의 공배수는 `FizzBuzz` 를 대신 출력하세요.",
    io: "- 입력: 정수 N\n- 출력: N줄",
    hint: "`FizzBuzz` 를 먼저 검사해야 합니다. 3의 배수를 먼저 걸러버리면 15가 `Fizz` 로 나옵니다.",
    answer: "n = int(input())\nfor i in range(1, n + 1):\n  if i % 15 == 0:\n    print(\"FizzBuzz\")\n  elif i % 3 == 0:\n    print(\"Fizz\")\n  elif i % 5 == 0:\n    print(\"Buzz\")\n  else:\n    print(i)",
    tests: [
      { stdin: "15", expected: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz", hidden: false },
      { stdin: "3", expected: "1\n2\nFizz", hidden: true },
      { stdin: "5", expected: "1\n2\nFizz\n4\nBuzz", hidden: true },
    ],
    published: true,
  },
  {
    order: 12,
    title: "함수로 가장 큰 수 찾기",
    concept: "def, return",
    body: "세 정수를 한 줄에 공백으로 구분해 입력받아 가장 큰 수를 출력하세요.\n**가장 큰 수를 돌려주는 함수를 직접 만들어서** 사용하세요.",
    io: "- 입력: 정수 세 개 (공백 구분)\n- 출력: 가장 큰 수",
    hint: "음수만 있을 때도 맞아야 합니다. `0` 부터 시작해 비교하면 여기서 틀립니다.",
    note: "채점은 **출력만** 봅니다. 함수를 안 쓰고 한 줄로 내도 통과합니다 — '함수를 쓰자'는 약속이지 강제가 아닙니다.",
    answer: "def biggest(a, b, c):\n  if a >= b and a >= c:\n    return a\n  elif b >= c:\n    return b\n  else:\n    return c\n\nx, y, z = map(int, input().split())\nprint(biggest(x, y, z))",
    tests: [
      { stdin: "3 9 5", expected: "9", hidden: false },
      { stdin: "-1 -5 -3", expected: "-1", hidden: true },
      { stdin: "7 7 7", expected: "7", hidden: true },
    ],
    published: true,
  },
  {
    order: 13,
    title: "초를 분과 초로 바꾸기",
    concept: "몫(//) 과 나머지(%)",
    body: "초 단위 시간을 입력받아 몇 분 몇 초인지 출력하세요.",
    io: "- 입력: 정수(초)\n- 출력: 첫째 줄 분, 둘째 줄 초",
    hint: "`//` 는 나눈 몫, `%` 는 나머지입니다. 60으로 나누면 몫이 분, 나머지가 초입니다.",
    answer: "n = int(input())\nprint(n // 60)\nprint(n % 60)",
    tests: [
      { stdin: "205", expected: "3\n25", hidden: false },
      { stdin: "60", expected: "1\n0", hidden: true },
      { stdin: "59", expected: "0\n59", hidden: true },
    ],
    published: true,
  },
  {
    order: 14,
    title: "카운트다운",
    concept: "while, 대입 연산자(-=)",
    body: "N을 입력받아 N부터 1까지 한 줄씩 세고, 마지막에 `발사!` 를 출력하세요.\n**while 문으로** 만드세요.",
    io: "- 입력: 정수 N\n- 출력: N줄 + 마지막 줄 `발사!`",
    hint: "`n -= 1` 을 빠뜨리면 무한 반복이 됩니다. 반복이 끝난 뒤에 `발사!` 를 출력해야 하니, 그 줄은 while 밖(들여쓰기 없이)에 있어야 합니다.",
    answer: "n = int(input())\nwhile n > 0:\n  print(n)\n  n -= 1\nprint(\"발사!\")",
    tests: [
      { stdin: "3", expected: "3\n2\n1\n발사!", hidden: false },
      { stdin: "1", expected: "1\n발사!", hidden: true },
      { stdin: "5", expected: "5\n4\n3\n2\n1\n발사!", hidden: true },
    ],
    published: true,
  },
  {
    order: 15,
    title: "피라미드 쌓기",
    concept: "중첩된 계산, 공백과 별 함께 쓰기",
    body: "N을 입력받아 가운데가 맞춰진 별 피라미드를 출력하세요.\n\n```\nN이 3일 때\n  *\n ***\n*****\n```",
    io: "- 입력: 정수 N\n- 출력: N줄",
    hint: "i번째 줄에는 앞에 공백이 (N-i)개, 별이 (2i-1)개 있습니다. 문자열끼리는 `+` 로 이어붙일 수 있습니다.",
    answer: "n = int(input())\nfor i in range(1, n + 1):\n  print(\" \" * (n - i) + \"*\" * (2 * i - 1))",
    tests: [
      { stdin: "3", expected: "  *\n ***\n*****", hidden: false },
      { stdin: "1", expected: "*", hidden: true },
      { stdin: "5", expected: "    *\n   ***\n  *****\n *******\n*********", hidden: true },
    ],
    published: true,
  },
  {
    order: 16,
    title: "점수 정렬하기",
    concept: "리스트, append, sort, reverse",
    body: "점수들을 입력받아 오름차순으로 정렬한 리스트와 내림차순으로 정렬한 리스트를 출력하세요.\n리스트를 그대로 `print` 하면 됩니다.",
    io: "- 입력: 첫째 줄 사람 수 N, 둘째 줄 점수 N개 (공백 구분)\n- 출력: 첫째 줄 오름차순 리스트, 둘째 줄 내림차순 리스트",
    hint: "`int()` 로 바꾼 뒤 `append()` 로 담아야 숫자로 정렬됩니다. 글자 그대로 담으면 `100` 이 `85` 보다 작다고 나옵니다.",
    answer: "n = int(input())\nscores = input().split()\n\nnumbers = []\nfor s in scores:\n  numbers.append(int(s))\n\nnumbers.sort()\nprint(numbers)\n\nnumbers.reverse()\nprint(numbers)",
    tests: [
      { stdin: "4\n90 85 100 75", expected: "[75, 85, 90, 100]\n[100, 90, 85, 75]", hidden: false },
      { stdin: "3\n1 3 2", expected: "[1, 2, 3]\n[3, 2, 1]", hidden: true },
      { stdin: "1\n50", expected: "[50]\n[50]", hidden: true },
    ],
    published: true,
  },
  {
    order: 17,
    title: "2차원 리스트의 줄별 합계",
    concept: "2차원 리스트, 중첩 반복문",
    body: "세 줄에 걸쳐 숫자가 세 개씩 주어집니다. 각 줄의 합을 한 줄씩 출력하세요.",
    io: "- 입력: 세 줄, 각 줄에 정수 세 개 (공백 구분)\n- 출력: 세 줄 (각 줄의 합)",
    hint: "먼저 세 줄을 리스트에 담고, 그 다음에 한 줄씩 꺼내 더합니다. 리스트 안에 리스트가 들어 있는 모양입니다.",
    answer: "table = []\nfor i in range(3):\n  row = input().split()\n  table.append(row)\n\nfor row in table:\n  total = 0\n  for x in row:\n    total += int(x)\n  print(total)",
    tests: [
      { stdin: "1 2 3\n4 5 6\n7 8 9", expected: "6\n15\n24", hidden: false },
      { stdin: "10 0 0\n0 0 0\n1 1 1", expected: "10\n0\n3", hidden: true },
    ],
    published: true,
  },
  {
    order: 18,
    title: "팩토리얼",
    concept: "함수, 반복(또는 재귀)",
    body: "N을 입력받아 N 팩토리얼(1부터 N까지 모두 곱한 값)을 출력하세요.\n**함수로 만들어서** 사용하세요.",
    io: "- 입력: 정수 N (1 이상)\n- 출력: N!",
    hint: "곱셈을 누적할 때 시작값은 0이 아니라 **1** 입니다. 0으로 시작하면 결과가 항상 0입니다.",
    note: "수업에서 배운 재귀 방식(`return n * fac(n-1)`)으로 풀어도 정답입니다.",
    answer: "def fac(n):\n  result = 1\n  for i in range(1, n + 1):\n    result *= i\n  return result\n\nnum = int(input())\nprint(fac(num))",
    tests: [
      { stdin: "5", expected: "120", hidden: false },
      { stdin: "1", expected: "1", hidden: true },
      { stdin: "10", expected: "3628800", hidden: true },
    ],
    published: true,
  },
  {
    order: 19,
    title: "최대공약수",
    concept: "반복문과 나머지 연산, 조건",
    body: "두 정수를 입력받아 최대공약수를 출력하세요.",
    io: "- 입력: 첫째 줄 a, 둘째 줄 b (둘 다 1 이상)\n- 출력: 최대공약수",
    hint: "1부터 a까지 훑으면서 **둘 다 나누어떨어지는** 수를 만날 때마다 답을 갱신하면, 마지막에 남는 값이 최대공약수입니다.",
    note: "수업에서 배운 유클리드 호제법(while 과 `m, n = n, r`)으로 풀면 훨씬 빠릅니다. 둘 다 정답입니다.",
    answer: "a = int(input())\nb = int(input())\n\ngcd = 1\nfor i in range(1, a + 1):\n  if a % i == 0 and b % i == 0:\n    gcd = i\n\nprint(gcd)",
    tests: [
      { stdin: "12\n18", expected: "6", hidden: false },
      { stdin: "7\n13", expected: "1", hidden: true },
      { stdin: "100\n75", expected: "25", hidden: true },
    ],
    published: true,
  },
  {
    order: 20,
    title: "3의 배수는 건너뛰기",
    concept: "continue",
    body: "1부터 N까지 한 줄씩 출력하되, 3의 배수는 출력하지 마세요.\n**continue 를 사용하세요.**",
    io: "- 입력: 정수 N\n- 출력: 3의 배수를 뺀 수들",
    hint: "`continue` 를 만나면 그 줄 아래는 건너뛰고 다음 반복으로 갑니다.",
    answer: "n = int(input())\nfor i in range(1, n + 1):\n  if i % 3 == 0:\n    continue\n  print(i)",
    tests: [
      { stdin: "10", expected: "1\n2\n4\n5\n7\n8\n10", hidden: false },
      { stdin: "3", expected: "1\n2", hidden: true },
      { stdin: "15", expected: "1\n2\n4\n5\n7\n8\n10\n11\n13\n14", hidden: true },
    ],
    published: true,
  },
]
